export const GET_HOUSES_SUCCESS = 'GET_HOUSES_SUCCESS';

//export const ADD_HOME = 'ADD_HOME';

export const POST_HOME_SUCCESS = "POST_HOME_SUCCESS";

export const REMOVE_HOME_SUCCESS = "REMOVE_HOME_SUCCESS";

export const POST_ROOM_SUCCESS = "POST_ROOM_SUCCESS";

export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS"

export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS"
